"""
Documentation Generator module for Vibe-Import.

This module generates documentation for generated packages,
including README files and API documentation.
"""

import re
from dataclasses import dataclass
from pathlib import Path

from vibe_import.models import GeneratedPackage, GeneratedFile
from vibe_import.extractor import ModuleSpec, FunctionSpec, ClassSpec


@dataclass
class DocSection:
    """A section of documentation."""
    title: str
    content: str
    level: int = 2  # Heading level (## by default)
    
    def to_markdown(self) -> str:
        """Convert to markdown string."""
        heading = "#" * self.level
        return f"{heading} {self.title}\n\n{self.content}"


class DocumentationGenerator:
    """
    Generates documentation for packages.
    """
    
    def __init__(self, include_examples: bool = True):
        self.include_examples = include_examples
    
    def generate_readme(
        self,
        package: GeneratedPackage,
        spec: ModuleSpec,
        original_code: str = "",
    ) -> str:
        """
        Generate a README.md for a package.
        
        Args:
            package: The generated package
            spec: The module specification
            original_code: Original code that used the package
            
        Returns:
            README content as markdown string
        """
        sections = []
        
        # Title and description
        sections.append(self._generate_header(package.name, spec))
        
        # Installation
        sections.append(self._generate_installation(package.name))
        
        # Quick start / Usage
        if original_code:
            sections.append(self._generate_usage(package.name, original_code))
        
        # API Reference
        sections.append(self._generate_api_reference(spec))
        
        # Examples
        if self.include_examples:
            sections.append(self._generate_examples(spec))
        
        # Combine all sections
        return "\n\n".join(s.to_markdown() for s in sections if s.content)
    
    def generate_api_docs(self, package: GeneratedPackage) -> str:
        """
        Generate API documentation from the package source code.
        
        Args:
            package: The generated package
            
        Returns:
            API documentation as markdown string
        """
        sections = []
        
        for file in package.files:
            if file.path.endswith('__init__.py'):
                continue
            
            file_docs = self._extract_docs_from_file(file)
            if file_docs:
                module_name = Path(file.path).stem
                sections.append(DocSection(
                    title=f"Module: {module_name}",
                    content=file_docs,
                    level=2,
                ))
        
        if not sections:
            return ""
        
        header = "# API Reference\n\n"
        return header + "\n\n".join(s.to_markdown() for s in sections)
    
    def _generate_header(self, name: str, spec: ModuleSpec) -> DocSection:
        """Generate the header section."""
        description = f"Auto-generated Python package `{name}`."
        
        # Try to infer purpose from spec
        purposes = []
        if spec.functions:
            func_names = [f.name for f in spec.functions[:3]]
            purposes.append(f"Functions: {', '.join(func_names)}")
        if spec.classes:
            class_names = [c.name for c in spec.classes[:3]]
            purposes.append(f"Classes: {', '.join(class_names)}")
        
        if purposes:
            description += "\n\n" + "\n".join(f"- {p}" for p in purposes)
        
        return DocSection(
            title=name,
            content=description,
            level=1,
        )
    
    def _generate_installation(self, name: str) -> DocSection:
        """Generate installation instructions."""
        content = f"""This package was auto-generated by [Vibe-Import](https://github.com/vibe-import/vibe-import).

To use this package, copy the `{name}/` directory to your project or add it to your Python path.

```bash
# Copy to your project
cp -r {name}/ /path/to/your/project/

# Or add to PYTHONPATH
export PYTHONPATH="${{PYTHONPATH}}:/path/to/{name}"
```"""
        
        return DocSection(title="Installation", content=content)
    
    def _generate_usage(self, name: str, original_code: str) -> DocSection:
        """Generate usage section from original code."""
        # Clean up the original code for display
        code = original_code.strip()
        
        content = f"""Here's how to use this package (based on the original code):

```python
{code}
```"""
        
        return DocSection(title="Quick Start", content=content)
    
    def _generate_api_reference(self, spec: ModuleSpec) -> DocSection:
        """Generate API reference section."""
        parts = []
        
        # Functions
        if spec.functions:
            parts.append("### Functions\n")
            for func in spec.functions:
                parts.append(self._format_function_doc(func))
        
        # Classes
        if spec.classes:
            parts.append("### Classes\n")
            for cls in spec.classes:
                parts.append(self._format_class_doc(cls))
        
        # Constants
        if spec.constants:
            parts.append("### Constants\n")
            for const in spec.constants:
                parts.append(f"- `{const.name}`: {const.inferred_type}")
        
        return DocSection(
            title="API Reference",
            content="\n\n".join(parts) if parts else "No public API documented.",
        )
    
    def _format_function_doc(self, func: FunctionSpec) -> str:
        """Format documentation for a function."""
        # Signature
        params = ", ".join(f"{name}: {type_hint}" for name, type_hint in func.parameters)
        signature = f"```python\ndef {func.name}({params}) -> {func.return_type}\n```"
        
        # Parameters table
        param_docs = []
        if func.parameters:
            param_docs.append("| Parameter | Type | Description |")
            param_docs.append("|-----------|------|-------------|")
            for name, type_hint in func.parameters:
                param_docs.append(f"| `{name}` | `{type_hint}` | - |")
        
        parts = [f"#### `{func.name}`\n", signature]
        if param_docs:
            parts.append("\n**Parameters:**\n")
            parts.append("\n".join(param_docs))
        parts.append(f"\n**Returns:** `{func.return_type}`")
        
        return "\n".join(parts)
    
    def _format_class_doc(self, cls: ClassSpec) -> str:
        """Format documentation for a class."""
        parts = [f"#### `{cls.name}`\n"]
        
        # Constructor
        init_params = ", ".join(f"{name}: {type_hint}" for name, type_hint in cls.init_parameters)
        parts.append(f"```python\nclass {cls.name}:\n    def __init__(self, {init_params})\n```\n")
        
        # Special capabilities
        capabilities = []
        if cls.is_context_manager:
            capabilities.append("Context Manager (supports `with` statement)")
        if cls.is_iterable:
            capabilities.append("Iterable (supports `for` loops)")
        
        if capabilities:
            parts.append("**Capabilities:** " + ", ".join(capabilities) + "\n")
        
        # Methods
        if cls.methods:
            parts.append("**Methods:**\n")
            for method in cls.methods:
                params = ", ".join(f"{n}: {t}" for n, t in method.parameters)
                parts.append(f"- `{method.name}({params}) -> {method.return_type}`")
        
        # Attributes
        if cls.attributes:
            parts.append("\n**Attributes:**\n")
            for name, type_hint in cls.attributes:
                parts.append(f"- `{name}`: `{type_hint}`")
        
        return "\n".join(parts)
    
    def _generate_examples(self, spec: ModuleSpec) -> DocSection:
        """Generate example usage section."""
        examples = []
        
        # Generate example for each function
        for func in spec.functions[:2]:  # Limit to 2 examples
            example = self._generate_function_example(func, spec.name)
            if example:
                examples.append(example)
        
        # Generate example for each class
        for cls in spec.classes[:2]:  # Limit to 2 examples
            example = self._generate_class_example(cls, spec.name)
            if example:
                examples.append(example)
        
        if not examples:
            return DocSection(title="Examples", content="")
        
        return DocSection(
            title="Examples",
            content="\n\n".join(examples),
        )
    
    def _generate_function_example(self, func: FunctionSpec, module: str) -> str:
        """Generate an example for a function."""
        # Generate sample arguments
        args = []
        for name, type_hint in func.parameters:
            args.append(self._generate_sample_value(name, type_hint))
        
        args_str = ", ".join(args)
        
        return f"""### Using `{func.name}`

```python
from {module} import {func.name}

result = {func.name}({args_str})
print(result)
```"""
    
    def _generate_class_example(self, cls: ClassSpec, module: str) -> str:
        """Generate an example for a class."""
        # Generate sample init arguments
        args = []
        for name, type_hint in cls.init_parameters:
            args.append(f"{name}={self._generate_sample_value(name, type_hint)}")
        
        args_str = ", ".join(args)
        
        lines = [
            f"### Using `{cls.name}`",
            "",
            "```python",
            f"from {module} import {cls.name}",
            "",
        ]
        
        if cls.is_context_manager:
            lines.append(f"with {cls.name}({args_str}) as obj:")
            for method in cls.methods[:2]:
                method_args = ", ".join(
                    self._generate_sample_value(n, t) 
                    for n, t in method.parameters
                )
                lines.append(f"    obj.{method.name}({method_args})")
        else:
            lines.append(f"obj = {cls.name}({args_str})")
            for method in cls.methods[:2]:
                method_args = ", ".join(
                    self._generate_sample_value(n, t) 
                    for n, t in method.parameters
                )
                lines.append(f"result = obj.{method.name}({method_args})")
        
        lines.append("```")
        
        return "\n".join(lines)
    
    def _generate_sample_value(self, name: str, type_hint: str) -> str:
        """Generate a sample value for a parameter."""
        type_lower = type_hint.lower()
        name_lower = name.lower()
        
        # Type-based samples
        if type_lower in ("int", "integer"):
            if "count" in name_lower or "num" in name_lower:
                return "10"
            if "id" in name_lower:
                return "1"
            return "42"
        
        if type_lower in ("float", "double"):
            return "3.14"
        
        if type_lower in ("str", "string"):
            if "path" in name_lower:
                return '"./data"'
            if "name" in name_lower:
                return '"example"'
            if "url" in name_lower:
                return '"https://example.com"'
            return f'"{name}_value"'
        
        if type_lower == "bool":
            return "True"
        
        if type_lower in ("list", "list[any]"):
            return "[1, 2, 3]"
        
        if type_lower in ("dict", "dict[str, any]"):
            return '{"key": "value"}'
        
        if type_lower == "none":
            return "None"
        
        # Default
        return "..."
    
    def _extract_docs_from_file(self, file: GeneratedFile) -> str:
        """Extract documentation from a Python file."""
        content = file.content
        docs = []
        
        # Extract module docstring
        module_doc = re.search(r'^"""(.*?)"""', content, re.DOTALL)
        if module_doc:
            docs.append(module_doc.group(1).strip())
        
        # Extract class and function signatures with docstrings
        # This is a simplified extraction - a full implementation would use AST
        
        # Find classes
        for match in re.finditer(
            r'^class\s+(\w+).*?:\s*\n\s*"""(.*?)"""',
            content,
            re.MULTILINE | re.DOTALL
        ):
            class_name = match.group(1)
            docstring = match.group(2).strip()
            docs.append(f"### {class_name}\n\n{docstring}")
        
        # Find functions
        for match in re.finditer(
            r'^def\s+(\w+)\s*\([^)]*\).*?:\s*\n\s*"""(.*?)"""',
            content,
            re.MULTILINE | re.DOTALL
        ):
            func_name = match.group(1)
            docstring = match.group(2).strip()
            if not func_name.startswith('_'):
                docs.append(f"### {func_name}\n\n{docstring}")
        
        return "\n\n".join(docs)
    
    def add_documentation_to_package(
        self,
        package: GeneratedPackage,
        spec: ModuleSpec,
        original_code: str = "",
    ) -> GeneratedPackage:
        """
        Add documentation files to a package.
        
        Args:
            package: The generated package
            spec: The module specification
            original_code: Original code that used the package
            
        Returns:
            Updated package with documentation
        """
        # Generate README
        readme_content = self.generate_readme(package, spec, original_code)
        package.documentation = readme_content
        
        # Add README.md file
        readme_file = GeneratedFile(
            path=f"{package.name}/README.md",
            content=readme_content,
        )
        
        # Check if README already exists
        existing_readme = package.get_file(f"{package.name}/README.md")
        if existing_readme:
            # Update existing
            for i, f in enumerate(package.files):
                if f.path == readme_file.path:
                    package.files[i] = readme_file
                    break
        else:
            package.files.append(readme_file)
        
        return package